modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="goety" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Goety" #mandatory
displayURL="https://github.com/Polarice3/Goety" #optional
logoFile="examplemod.png" #optional
credits="Tutorial/Help: Technovision, Cy4's Modding, TelepathicGrunt, diesieben07.
        Github Codes: Vazkii, williewillus, Hubry, TheIllusiveC4, CFGrafanaStats, Alex666, hollingsworth, baileyholl, Lothrazar, DenisMasterHerobrine, Ellpeck,
        owmii, elucent, WayofTime, stal111, The Grey Ghost, HellFirePvP, klikli-dev, Qelifern, vemerion, MrCrayfish, Ipsis, TeamTwilight"
authors="Polarice3" #optional
description='''
Goety adds a bunch of new Mobs that can help or hinder players and a magic system that can provides a player a different way of combat!
'''
[[dependencies.goety]] #optional
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[35,)" #mandatory

    ordering="NONE"

    side="BOTH"
[[dependencies.goety]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
